version: "3.9"
services:
  asterisk:
    image: ast
    container_name: asterisk
    network_mode: host
    command: sleep infinity
    #command: asterisk -cvvvvv
    working_dir: /etc/asterisk
    volumes:
      - ./etc/asterisk:/etc/asterisk
      - ./recording:/var/spool/asterisk/recording
    #environment:
    #  - http_proxy=http://127.0.0.1:7890
    #  - https_proxy=http://127.0.0.1:7890
    #  - all_proxy=http://127.0.0.1:7890
