version: "3.9"
services:
  asterisk:
    image: ast
    container_name: asterisk
    network_mode: host
    command: sleep infinity
    #command: asterisk -cvvvvv
    working_dir: /etc/asterisk
    volumes:
      - ./etc/asterisk:/etc/asterisk
